version: "3.9"
services:
  timemachine:
      image: dperson/samba
      container_name: timemachine
      restart: always
      ports:
        - '138:138/udp'
        - '137:137/udp'
        - '139:139'
        - '445:445'
      volumes:
        - './timemachine/samba.conf:/samba.conf'
        - './timemachine/data:/mnt/time-machine/'
      command: "-p -n -I /samba.conf -u \"${TM_USER:?err};${TM_PASS:?err}\" -s \"samba;/mnt/time-machine/;yes;no;no;$USER\""
      
  plex:
    image: plexinc/pms-docker
    container_name: plex
    ports:
        - '32400:32400/tcp'
        - '3005:3005/tcp'
        - '8324:8324/tcp'
        - '32469:32469/tcp'
        - '1900:1900/udp'
        - '32410:32410/udp'
        - '32412:32412/udp'
        - '32413:32413/udp'
        - '32414:32414/udp'
    environment:
        - TZ=<timezone>
        - ADVERTISE_IP=http://station/
    volumes:
        - ./plex/config:/config
        - ./plex/transcode:/data/transcode
        - ./medias/movies:/data/movies
        - ./medias/tvshows:/data/tvshows
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./scripts:/scripts
      - ./radarr/config:/config
      - ./medias/movies:/movies
      - ./radarr/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./scripts:/scripts
      - ./sonarr/config:/config
      - ./medias/tvshows:/tv
      - ./sonarr/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/transmission/ 
    volumes:
      - /transmission/data:/config
      - /transmission/downloads:/downloads
      - /transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
networks: 
  default: 
    name: infra-si
