version: "3.9"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    ports:
        - '32400:32400/tcp'
        - '3005:3005/tcp'
        - '8324:8324/tcp'
        - '32469:32469/tcp'
        - '1900:1900/udp'
        - '32410:32410/udp'
        - '32412:32412/udp'
        - '32413:32413/udp'
        - '32414:32414/udp'
    environment:
        - TZ=<timezone>
        - PLEX_CLAIM=<claimToken>
        - ADVERTISE_IP=http://station/
    volumes:
        - ./plex/config:/config
        - ./plex/transcode:/transcode
        - ./medias:/movies
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./scripts:/scripts
      - ./radarr/config:/config
      - ./medias:/movies #optional
      - ./radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./scripts:/scripts
      - ./sonarr/config:/config
      - ./medias:/tv #optional
      - ./sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

networks: 
  default: 
    name: infra-si
